name: Checks
on: pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run lint checks
        run: |
          sudo apt-get update
          sudo apt-get install libsuitesparse-dev
          sudo echo "C_PATH=/usr/local/include/suitesparse" >> /etc/environment
          sudo echo "LIBRARY_PATH=/usr/local/lib" >> /etc/environment
          sudo echo "LD_LIBRARY_PATH=/usr/local/lib" >> /etc/environment
          sudo apt-get install clang
          sudo apt-get install bear
          bear -- make examples
          make lint
